### ISSUE TITLE
Button mapper issue when re-connecting controller via wireless xbox adapter

### ISSUE THREAD

**Issue by BonesJones94** [Adam777Z/xbox-controller-button-remapper#6]
Hi there, really like using the button mapper tool, and love the fact you can initiate multiple functions for the share button! I have however found a slight problem while using it on my setup of a microsoft xbox wireless controller adapter,
I can sync up the controller and use it while having button mapper open no problem and the button mapper tool works perfectly, but i have found that if the controller is turned off or disconnects while button mapper is still running I cannot re-connect the controller. It looks like it connects for a split second and i have confirmed it does using the xbox accessories app, the controller is recognised but then disconnects and turns off. Its not that big of an issue as the controller re-connects properly after closing button mapper and im able to open it again to continue but just in case you had any thoughts on what might cause this?
Cheers, Ryan

**Comment by robbely** [comment]
I came here to say exactly the same thing! It took forever to realise it was this app and not a faulty cable or faulty port.

If you stop the app and try to reconnect again it works fine but if the controller powers off again the issue returns.

**Comment by Mecak** [comment]
Hi, me too I have the same issue with the wireless xbox adapter, it works with Bluetooth
But it turns off directly the controller when using the adapter

**Comment by vimiani** [comment]
I also have this issue, please fix.

**Comment by vimiani** [comment]
- Application version 1.4.0.0, but I remember trying at least a couple older versions and this still happening
- Windows 10 Pro Version 2004
- 1914
- The older, larger adapter
- Controller is on the latest firmware

**Comment by vimiani** [comment]
> * Application version 1.4.0.0, but I remember trying at least a couple older versions and this still happening
> * Windows 10 Pro Version 2004
> * 1914
> * The older, larger adapter
> * Controller is on the latest firmware

After a little bit of additional testing, this seems to happen on my older 1708 controller as well, had to dig it back out to test.

**Comment by robbely** [comment]
Is there any update? Was the additional information helpful?

**Comment by Adam777Z** [comment]
Yes, it was helpful.

Can anyone try the other Controller models?

**Comment by Adam777Z** [comment]
This issue does not happen with the Xbox Controller model 1697 and Xbox Wireless Adapter model 1713.

**Comment by V3ntilator** [comment]
I think i know why it doesn't work for me and some others.
Windows 10 don't support the share button. It's exclusive to Windows 11.

Steam itself have native support for Share button, but that one is buggy too as it takes screenshots instead of the remapping to record of video.

**Comment by Adam777Z** [comment]
This issue is fixed in version [1.5.0.0](https://github.com/Adam777Z/xbox-controller-button-remapper/releases/tag/1.5.0.0).

**Comment by robbely** [comment]
Many thanks for the fix - works great now :)

**Comment by V3ntilator** [comment]
1.5.0.0 didn't fix it for me.
Here is all i tried.
- Windows 10 is 100% up to date.
- Xbox Gamepad uses newest firmware. Updated it again in Windows 10 yesterday (Xbox Accessories)
- I re-installed VC_redist.x64.exe (2022) from link in "Readme" and rebooted

- I use share_key = 56,68 (Left ALT + F10) ( , (51) on Numpad didn't work either)
- Xbox Pad were powered on before i started Remapper
- I tried wireless and wired.
- Share button works, because Steam detects it without Xbox Button Remapper.

**Comment by V3ntilator** [comment]
1.5.0.0 didn't fix it for me.
Here is all i tried.
- Windows 10 is 100% up to date.
- Xbox Gamepad uses newest firmware. Updated it again in Windows 10 yesterday (Xbox Accessories)
- I re-installed VC_redist.x64.exe (2022) from link in "Readme" and rebooted

- I use share_key = 56,68 (Left ALT + F10) ( , (51) on Numpad didn't work either)
- Xbox Pad were powered on before i started Remapper every time
- I tried this wireless and wired. (Wireless with official Win 10 USB Wireless Xbox Dongle)
- Also tried short and long presses
- Share button works, because Steam detects it without Xbox Button Remapper.

"I use share_key = 56,68 (Left ALT + F10) ( , (51) on Numpad didn't work either)"
Perhaps i did something wrong here?

**Comment by V3ntilator** [comment]
This thread is just waste of time as GitHub auto marks everything as off topic.
Finally got the remapping to work with Steam and NVIDIA Shadowplay, so i don't need this non working app anymore.

**Comment by Adam777Z** [comment]
> 1.5.0.0 didn't fix it for me. Here is all i tried.
> 
>     * Windows 10 is 100% up to date.
> 
>     * Xbox Gamepad uses newest firmware. Updated it again in Windows 10 yesterday (Xbox Accessories)
> 
>     * I re-installed VC_redist.x64.exe (2022) from link in "Readme" and rebooted
> 
>     * I use share_key = 56,68 (Left ALT + F10) ( , (51) on Numpad didn't work either)
> 
>     * Xbox Pad were powered on before i started Remapper every time
> 
>     * I tried this wireless and wired. (Wireless with official Win 10 USB Wireless Xbox Dongle)
> 
>     * Also tried short and long presses
> 
>     * Share button works, because Steam detects it without Xbox Button Remapper.
> 
> 
> "I use share_key = 56,68 (Left ALT + F10) ( , (51) on Numpad didn't work either)" Perhaps i did something wrong here?

You are commenting in the wrong place.
See the issue (#7) you created and my reply there:
> This program works on Windows 10/11 64-bit to remap the Xbox/Guide button and/or Share button on the Xbox Controller.
> 
> Support is available under [Discussions](https://github.com/Adam777Z/xbox-controller-button-remapper/discussions) in [Help](https://github.com/Adam777Z/xbox-controller-button-remapper/discussions/2).

Make sure you have this setting disabled for it to work:
Settings - Gaming - Xbox Game Bar - Open Xbox Game Bar using this button on a controller: (X)
